apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-counter-application
  labels:
    app: python-counter-application
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python-counter-application
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: python-counter-application
    spec:
      containers:
      - name: python-counter-application
        image: python-counter-application:0.1.0